### ISSUE TITLE
Are there plans to support new versions of JS?

### ISSUE THREAD

**Issue by bigos** [vsedach/Parenscript#35]
I can understand the need to have the same code on the front and the back end, but do you have any plans to support new versions of JS or show how can I hack it myself?

**Comment by jasom** [comment]
Well we trivially support it since it's backwards compatible.

As far as exposing new features, ES2015 contains a *lot* of new syntax.  I am open for proposals for how to expose it in a lispy manner, and will be happy to help to implement them.

The general guidelines are:

- No library required to run parenscript
- Simple things should look like reasonable javascript: e.g. consider the output of `(ps:ps (loop for i from 1 to 10 collect i))` or `(setf x 3)`
- *js-target-version* should be respected (it's fine to e.g. signal an error if someone tries to create ES2015 classes with it set to something earlier).

**Comment by vsedach** [comment]
Agree with @jasom. My plan is to make a 2.7 release soon, and then start merging in changes for ES6 support from @jasom and Clint Moore, to go into a 2.8 release.
