### ISSUE TITLE
Duplicated variable initialization with multiple COLLECT clauses into same result

### ISSUE THREAD

**Issue by phmarek** [vsedach/Parenscript#46]
```lisp
(ps:ps
    (loop for i from 0 to 3
          for ch = (char "abcde" i)
          for p = (char-code ch)
          collect (logand (ash p -1) 1)
          collect (logand (ash p -0) 1)))
```
results in
```javascript
(function () {
    var collect41 = [];
    var collect41 = [];
    for (var i = 0; i <= 3; i += 1) {
        var ch = char('abcde', i);
        var p = charCode(ch);
        collect41.push(p >> 1 & 1);
        collect41.push(p >> 0 & 1);
    };
    __PS_MV_REG = [];
    return collect41;
})();
```

Please note the duplicated `var collect41` statements.

I don't think this breaks JS, but at least it is ugly.

**Comment by vsedach** [comment]
I recorded this issue in https://gitlab.common-lisp.net/parenscript/parenscript/commit/526346549f0342d67947d360a8f7ba9fc7b09e54

I am going to delete this GitHub project (I am minimizing use of
GitHub since Microsoft now owns this website). You can follow up on
the mailing list:
parenscript-devel@common-lisp.net
Subscription instructions:
https://mailman.common-lisp.net/listinfo/parenscript-devel

Or on the common-lisp.net GitLab instance:
https://gitlab.common-lisp.net/parenscript/parenscript
